--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AlexPads/ShopUI-FormAPI-Working
build-by-default: true
branches:
- master
projects:
  ShopUI-FormAPI-Working:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.0.0
php-stan: false
...
