--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AlexPads/ShopUI-FormAPI-Working
build-by-default: true
branches:
- master
projects:
  CustomShopUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.1.2
...
